import * as z from 'zod';

const CtSchema = z.object({
    rounds_played: z.number().optional(),
    rounds_won: z.number().optional(),
    rounds_survived: z.number().optional(),
    mvps: z.number().optional(),
    kills: z.number().optional(),
    deaths: z.number().optional(),
    deaths_from_players: z.number().optional(),
    assists: z.number().optional(),
    kast: z.number().optional(),
    rws: z.number().optional(),
    adr: z.number().optional(),
    kd: z.number().optional(),
    kr: z.number().optional(),
    smokes: z.number().optional(),
    flashes: z.number().optional(),
    burners: z.number().optional(),
    hes: z.number().optional(),
    enemies_flashed: z.number().optional(),
    flash_assists: z.number().optional(),
    team_flashes: z.number().optional(),
    enemy_blind_time: z.string().optional(),
    team_blind_time: z.string().optional(),
    utility_unused: z.number().optional(),
    utility_thrown: z.number().optional(),
    utility_success: z.number().optional(),
    utility_dmg: z.number().optional(),
    utility_dmg_received: z.number().optional(),
    utility_team_dmg: z.number().optional(),
    utility_team_dmg_received: z.number().optional(),
    he_dmg: z.number().optional(),
    burner_dmg: z.number().optional(),
    self_utility_damage: z.number().optional(),
    smokes_unused: z.number().optional(),
    decoy: z.number().optional(),
    decoy_unused: z.number().optional(),
    burner_thrown_at_team: z.number().optional(),
    burner_received_from_team: z.number().optional(),
    burner_received_from_self: z.number().optional(),
    burner_dmg_received_from_self: z.number().optional(),
    burner_received: z.number().optional(),
    burner_unused: z.number().optional(),
    burner_success: z.number().optional(),
    burner_dmg_received: z.number().optional(),
    burner_team_dmg: z.number().optional(),
    burner_team_dmg_received: z.number().optional(),
    he_dmg_received: z.number().optional(),
    he_team_dmg_received: z.number().optional(),
    he_thrown_at_team: z.number().optional(),
    he_team_dmg: z.number().optional(),
    he_received_from_team: z.number().optional(),
    he_damage_received_from_team: z.number().optional(),
    he_received_from_self: z.number().optional(),
    he_damage_received_from_self: z.number().optional(),
    he_unused: z.number().optional(),
    he_success: z.number().optional(),
    smokes_thrown_with_team: z.number().optional(),
    flashed_self: z.number().optional(),
    self_flash_assist: z.number().optional(),
    flashed_by_self_duration: z.string().optional(),
    flashed_by_team: z.number().optional(),
    flashed_by_team_duration: z.string().optional(),
    flashed_by_enemy: z.number().optional(),
    flashed_by_enemy_duration: z.string().optional(),
    assisted_flash: z.number().optional(),
    flash_success: z.number().optional(),
    unused_flashes: z.number().optional(),
    blind_kills: z.number().optional(),
    damage: z.number().optional(),
    hs_kills: z.number().optional(),
    hs_rate: z.number().optional(),
    accuracy: z.number().optional(),
    shots: z.number().optional(),
    hits: z.number().optional(),
    spotted_shots: z.number().optional(),
    spotted_hits: z.number().optional(),
    spotted_accuracy: z.number().optional(),
    multi_kills: z.number().optional(),
    multi_kills_rate: z.number().optional(),
    aces: z.number().optional(),
    quadra_kills: z.number().optional(),
    triple_kills: z.number().optional(),
    double_kills: z.number().optional(),
    single_kills: z.number().optional(),
    entry_kills: z.number().optional(),
    entry_deaths: z.number().optional(),
    entry_diff: z.number().optional(),
    entry_attempts: z.number().optional(),
    entry_attempts_rate: z.number().optional(),
    entry_success_rate: z.number().optional(),
    trade_kills: z.number().optional(),
    deaths_traded: z.number().optional(),
    entry_kills_traded: z.number().optional(),
    entry_deaths_traded: z.number().optional(),
    clutch_rounds: z.number().optional(),
    clutch_rounds_won: z.number().optional(),
    clutch_rounds_lost: z.number().optional(),
    clutch_success_rate: z.number().optional(),
    wins1v5: z.number().optional(),
    loss1v5: z.number().optional(),
    wins1v4: z.number().optional(),
    loss1v4: z.number().optional(),
    wins1v3: z.number().optional(),
    loss1v3: z.number().optional(),
    wins1v2: z.number().optional(),
    loss1v2: z.number().optional(),
    wins1v1: z.number().optional(),
    loss1v1: z.number().optional(),
    team_kills: z.number().optional(),
    team_damage: z.number().optional(),
});

const PlayerSchema = z.object({
    player_id: z.string(),
    elo: z.number(),
    crosshair: z.string(),
    total: CtSchema,
    t: CtSchema,
    ct: CtSchema,
});

const TeamSchema = z.object({
    team_id: z.string().optional(),
    score: z.number().optional(),
    first_half_score: z.number().optional(),
    second_half_score: z.number().optional(),
    players: z.array(PlayerSchema).optional(),
});

const Cs2Schema = z.object({
    teams: z.array(TeamSchema),
    mvp_player_id: z.string(),
});

const PayloadSchema = z.object({
    id: z.string(),
    game: z.string(),
    match_round_number: z.number(),
    cs2: Cs2Schema,
});

export const MatchStatisticsSchema = z.object({
    payload: PayloadSchema,
});
export type MatchStatistics = z.infer<typeof MatchStatisticsSchema>;
